# NumPy

In [10]:
import numpy as np
arr=np.array([12,22,32,34,55,65])
print(arr,"\n",type(arr))
print("which ordere array? :",arr.ndim)


[12 22 32 34 55 65] 
 <class 'numpy.ndarray'>
which ordere array? : 1


# Time Module

In [28]:
import time
def dce():
    i=0
    while i<500:
        print('A')
        i+=1

def beu():
    for i in range(500):
        print('B')
        i+=1
t1=time.time()
dce()
print(time.time()-t1)
t2=time.time()
beu()
print(time.time()-t2)

A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A


In [32]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([6,5,4,3,2,1])

t1=time.time()
print(arr1)
print(time.time()-t1)


t2=time.time()
time.sleep(5)
print(arr2)
print(time.time()-t2)

[1 2 3 4 5 6]
0.0
[6 5 4 3 2 1]
5.004620790481567


In [23]:
import time as t
t.sleep(3)
print("Hello")

Hello


# Array.

In [33]:
arr=np.array([12,23,34,45,67])
arr

array([12, 23, 34, 45, 67])

In [37]:
l=[]
for i in range(0,5,1):
    num=int(input("Enter number: "))
    l.append(num)

print("Array is: ",np.array(l))

Enter number:  123654
Enter number:  45
Enter number:  47
Enter number:  89
Enter number:  78


Array is:  [123654     45     47     89     78]


# 1,2,3-D Array

In [40]:
arr=np.array([12,21,23,322,34])
print(arr)
print(type(arr))
print(arr.ndim,"- D Array")

[[ 12  21  23 322  34]]
<class 'numpy.ndarray'>
2 - D Array


In [41]:
arr2=np.array([[12,21,34],[433,67,87,]])
print(arr2)
print(type(arr2))
print(arr2.ndim,"- D Array")

[[ 12  21  34]
 [433  67  87]]
<class 'numpy.ndarray'>
2 - D Array


In [46]:
arr2=np.array([[12,21,34],[433,67,87,],[34,33,5]])
print(arr2)
print(type(arr2))
print(arr2.ndim,"- D Array")

[[ 12  21  34]
 [433  67  87]
 [ 34  33   5]]
<class 'numpy.ndarray'>
2 - D Array


In [45]:
arr3=np.array([[[12,21,34],[433,67,87,],[34,33,5]]])
print(arr3)
print(type(arr3))
print(arr3.ndim,"- D Array")

[[[ 12  21  34]
  [433  67  87]
  [ 34  33   5]]]
<class 'numpy.ndarray'>
3 - D Array


# 10-D Array

In [47]:
arr=np.array([23,43,456,775],ndmin=10)
print(arr)
print(type(arr))
print(arr.ndim)

[[[[[[[[[[ 23  43 456 775]]]]]]]]]]
<class 'numpy.ndarray'>
10


# Array Filled With zeros

In [56]:
arr1=np.zeros(4)

arr2=np.zeros((5,4))

print(arr1)
print(arr1.ndim)

print()

print(arr2)
print(arr2.ndim)

[0. 0. 0. 0.]
1

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


# Ones

In [58]:
arr=np.ones(5)
print(arr)
print(type(arr))
print(arr.ndim)

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
1


In [60]:
arr=np.ones((5,4))
print(arr)
print(type(arr))
print(arr.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
2


In [62]:
arr=np.ones((5,5))
print(arr)
print(type(arr))
print(arr.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
2


# Empty Array

In [63]:
arr=np.empty(5)
print(arr)
print(type(arr))
print(arr.ndim)

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
1


In [65]:
arr=np.empty((5,5))
print(arr)
print(type(arr))
print(arr.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
2


# Range

In [66]:
arr=np.arange(5)
print(arr)
print(type(arr))
print(arr.ndim)

[0 1 2 3 4]
<class 'numpy.ndarray'>
1


In [68]:
arr=np.arange((5))
print(arr)
print(type(arr))
print(arr.ndim)

[0 1 2 3 4]
<class 'numpy.ndarray'>
1


# Diagonal Matrix

In [70]:
arr=np.eye(5)
print(arr)
print(type(arr))
print(arr.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>
2


# Linspace

In [73]:
arr=np.linspace(5,100,num=20)
print(arr)
print(type(arr))
print(arr.ndim)

[  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.
  75.  80.  85.  90.  95. 100.]
<class 'numpy.ndarray'>
1


# Create NumPy Array with Random Numbers

## Rand

b/w to 0 to 1

In [82]:
arr=np.random.rand(4,10)
print(arr)
print(type(arr))
print(arr.ndim)

[[0.94657912 0.43243859 0.87427372 0.70044959 0.98739576 0.45204305
  0.82816273 0.42692407 0.59163246 0.40257903]
 [0.24629847 0.83070521 0.90147442 0.52396029 0.71847173 0.55955311
  0.21074268 0.79706649 0.03605004 0.95355228]
 [0.45867286 0.98627605 0.13299333 0.71951901 0.59867505 0.27873831
  0.14849064 0.45663365 0.62441767 0.87021991]
 [0.02547583 0.16598566 0.47259519 0.94607087 0.72048487 0.47498217
  0.95390999 0.40821638 0.47005215 0.10640261]]
<class 'numpy.ndarray'>
2


# Randn

In [84]:
arr=np.random.randn(4,4)
print(arr)
print(type(arr))
print(arr.ndim)

[[-0.84443668 -0.47205153 -1.37987584  0.89431109]
 [-0.02418255 -0.89781961 -0.88149159 -0.56675164]
 [ 0.18402996  1.12891348  1.24709986 -2.07728286]
 [-1.71397769 -0.08357193  0.0158125  -0.80753826]]
<class 'numpy.ndarray'>
2


# Ranf

Return array [0.0,1.0)

In [86]:
arr=np.random.ranf((3,4))
print(arr)
print(type(arr))
print(arr.ndim)

[[0.09396494 0.33810578 0.5776877  0.51599778]
 [0.96428278 0.79131438 0.93058441 0.03096305]
 [0.10851858 0.43725744 0.88531351 0.36563806]]
<class 'numpy.ndarray'>
2


# Randint

Generate number will be a give range.

In [91]:
arr=np.random.randint(10,50,10)
print(arr)
print(type(arr))
print(arr.ndim)

[30 10 27 17 38 48 21 23 12 19]
<class 'numpy.ndarray'>
1


# Data Types in NumPy Arrays

In [92]:
arr=np.array([23,32,45,56,78,89])
print(arr.dtype)
print(type(arr))
print(arr.ndim)

int32
<class 'numpy.ndarray'>
1


In [99]:
arr=np.array([3,2.5])
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)

float64
<class 'numpy.ndarray'>
1


In [101]:
arr=np.array([23,32,45,56,78,89,"Birbal"])
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)

['23' '32' '45' '56' '78' '89' 'Birbal']
<U11
<class 'numpy.ndarray'>
1


# Shape & Reshaping in NumPy Arrays

### Shape

In [105]:
arr=np.array([[12,21,34,54,56],[43,56,78,998,65]],ndmin=3)
print(arr)
print("order is: ",arr.shape)
print(type(arr))
print(arr.ndim)

[[[ 12  21  34  54  56]
  [ 43  56  78 998  65]]]
order is:  (1, 2, 5)
<class 'numpy.ndarray'>
3


### Reshaping

In [107]:
arr=np.array([12,32,45,65,78,87])
y=arr.reshape(2,3)
print(y)

[[12 32 45]
 [65 78 87]]


# Arithmetic Operation in NumPy Arrays

In [7]:
import numpy as np
var1=np.array([12,43,54,67])
var2=np.array([1,65,52,68])
print(var1)
print()
print(var2)

print("addition is: ",var1+var2)



[12 43 54 67]

[ 1 65 52 68]
addition is:  [ 13 108 106 135]


In [3]:
print("multip. is: ",var1*var2)

multip. is:  [ 648 2795 2808 4556]


In [4]:
Birbal=var1%5
print(Birbal)

[2 3 4 2]


In [8]:
rec=np.reciprocal(var2)
print(rec)

[1 0 0 0]


# 2D array

In [9]:
var1=np.array([[1,2,3,4],[5,6,7,8]])
var2=np.array([[4,3,2,1],[9,8,7,7]])
print(var1+var2)

[[ 5  5  5  5]
 [14 14 14 15]]


# Arithmetic Function

In [12]:
x=np.array([23,43,56,75,-78])
print("Minimum ele: ",np.min(x))

Minimum ele:  -78


In [20]:
print("Maximum ele: ",np.max(x))
print("sqrt: ",np.sqrt(x))

Maximum ele:  75
sqrt:  [4.79583152 6.55743852 7.48331477 8.66025404        nan]


C:\Users\birba\AppData\Local\Temp\ipykernel_25264\459668609.py:2: RuntimeWarning: invalid value encountered in sqrt
  print("sqrt: ",np.sqrt(x))


In [15]:
print("Maximum ele: ",np.max(x),np.argmax(x))
print("Minimum ele: ",np.min(x),np.argmin(x))

Maximum ele:  75 3
Minimum ele:  -78 4


In [18]:
y=np.array([[1,2,3,4],[8,7,6,5]])
print(np.min(y,axis=0))

[1 2 3 4]


In [21]:
print(np.sin(x))

[-0.8462204  -0.83177474 -0.521551   -0.38778164 -0.51397846]


In [22]:
print(np.cos(x))

[-0.53283302  0.5551133   0.85322011  0.92175127 -0.85780309]


In [23]:
print(np.tan(x))

[ 1.58815308 -1.49838734 -0.61127369 -0.42070095  0.59918   ]


# Broadcasting Numpy arrays

In [28]:
import numpy as np
v1=np.array([12,33,44,54,65])
v2=np.array([43,56,76,87])
print(v1+v2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

#### shape

In [29]:
var2=np.array([23,45,65,56])
print(var2.shape)

(4,)


In [30]:
var2=np.array([[23,45,65,56],[43,55,76,78]])  # first is row and second is columns
print(var2.shape)

(2, 4)


# Indexing NumPy Array

In [31]:
v1=np.array([34323,5434,6,7])
print(v1[3])

7


In [32]:
print(v1[-3])

5434


In [33]:
v1=np.array([[34323,5434,6,7],[23,54,5,65]])
print(v1)
print()
print(v1.ndim)
print()
print(v1[0,1])

[[34323  5434     6     7]
 [   23    54     5    65]]

2

5434


In [35]:
v1=np.array([[34323,5434,6,7],[23,54,5,65],[23,54,66,77]])
print(v1)
print()
print(v1.ndim)
print()
print(v1[2,2])

[[34323  5434     6     7]
 [   23    54     5    65]
 [   23    54    66    77]]

2

66


# Slicing NumPy array

In [36]:
import numpy as np
v1=np.array([2,3,4,3,65,6,75])
print(v1)
print()

print("2 to 5",v1[1:5])

[ 2  3  4  3 65  6 75]

2 to 5 [ 3  4  3 65]


In [37]:
v1=np.array([2,3,4,3,65,6,75])
print(v1)
print()

print("2 to 5",v1[1:5:2])

[ 2  3  4  3 65  6 75]

2 to 5 [3 3]


In [38]:
v1=np.array([2,3,4,3,65,6,75])
print(v1)
print()

print("2 to 5",v1[1:])

[ 2  3  4  3 65  6 75]

2 to 5 [ 3  4  3 65  6 75]


In [39]:
v1=np.array([2,3,4,3,65,6,75])
print(v1)
print()

print("2 to 5",v1[:5])

[ 2  3  4  3 65  6 75]

2 to 5 [ 2  3  4  3 65]


In [40]:
v1=np.array([2,3,4,3,65,6,75])
print(v1)
print()

print("2 to 5",v1[::3])

[ 2  3  4  3 65  6 75]

2 to 5 [ 2  3 75]


In [42]:
v1=np.array([[2,3,4,3],[23,45,66,77],[56,78,98,65]])
print(v1)
print()

print(v1[1,1:])

[[ 2  3  4  3]
 [23 45 66 77]
 [56 78 98 65]]

[45 66 77]


# Iterating NumPy Array

In [44]:
v1=np.array([[[2,3,4,3],[23,45,66,77],[56,78,98,65]]])
for i in v1:
    print(i)

[[ 2  3  4  3]
 [23 45 66 77]
 [56 78 98 65]]


In [3]:
import numpy as np
v1=np.array([[[2,3,4,3],[23,45,66,77],[56,78,98,65]]])
for i in np.nditer(v1,flags=['buffered'],op_dtypes=["s"]):
    print(i)

TypeError: Field elements must be 2- or 3-tuples, got ''s''

# Copy and View in Numpy Arrays

copy means, it is not change original array but view is change original arrays

In [7]:
var=np.array([12,32,44,56])
print(type(var))
print(var)
print(" ")
co=var.copy()
co[3]=500
print(co)

<class 'numpy.ndarray'>
[12 32 44 56]
 
[ 12  32  44 500]


In [9]:
var2=np.array([23,43,56,765])
vie=var2.view()
vie[2]=100

print("original array:",var2)
print("change array: ",vie)
print()
print("Now original array is change:",var2)

original array: [ 23  43 100 765]
change array:  [ 23  43 100 765]

Now original array is change: [ 23  43 100 765]


# Join & Split Function in Numpy Arrays


Join means, it add two or more array
and Split means break array

In [15]:
var1=np.array([12,32,345,32])
var2=np.array([34,54,56,76])
arr=np.concatenate((var1,var2))
print(arr)

[ 12  32 345  32  34  54  56  76]


In [16]:
var1=np.array([[12,32,345,32],[23,54,67,65]])
var2=np.array([[34,54,56,76],[34,65,655,66]])
arr=np.concatenate((var1,var2),axis=1)
print(arr)

[[ 12  32 345  32  34  54  56  76]
 [ 23  54  67  65  34  65 655  66]]


# Split Array

In [20]:
arr=np.array([12,33,45,66,78,88,89,9,43])
newa=np.array_split(arr,4)
print(newa[2])
print(newa)

[88 89]
[array([12, 33, 45]), array([66, 78]), array([88, 89]), array([ 9, 43])]


## Search,sort,search sorted,Filter

In [24]:
arr=np.array([23,2,45,6,76,766,55,89,90])
x=np.where(arr>23)
print(x)

(array([2, 4, 5, 6, 7, 8], dtype=int64),)


In [25]:
y=np.where(arr%5==0)
print(y)

(array([2, 6, 8], dtype=int64),)


### sort

In [26]:
z=np.sort(arr)
print(z)

[  2   6  23  45  55  76  89  90 766]


In [31]:
ar=np.array([[[21,3,4],[15,7,8],[562,87,98]]])
print(np.sort(ar))


[[[  3   4  21]
  [  7   8  15]
  [ 87  98 562]]]


In [29]:
str=np.array(['b','i','r','b','a','l'])
print(np.sort(str))

['a' 'b' 'b' 'i' 'l' 'r']


## Filter

In [33]:
str=np.array(['b','i','r','b','a','l'])
f=[True,False,False,True,True,True]
new_str=str[f]
print(new_str)

['b' 'b' 'a' 'l']


In [34]:
graph = {
    'a': {'b': 1, 'c': 6, 'd': 5},
    'b': {'a': 1, 'c': 6},
    'c': {'a': 6, 'b': 6, 'd': 3, 'e': 7},
    'd': {'a': 5, 'c': 3, 'f': 2, 'g': 10},
    'e': {'c': 7, 'h': 12},
    'f': {'d': 2, 'h': 8},
    'g': {'d': 10, 'h': 7, 'i': 3},
    'h': {'e': 12, 'f': 8, 'g': 7, 'i': 8},
    'i': {'g': 3, 'h': 8},
}

def prims_algorithm(graph):
    start_node = 'a'
    visited = {start_node}
    edge_list = []
    total_cost = 0

    while len(visited) < len(graph):
        min_edge = None
        min_cost = float('inf')

        for node in visited:
            for neighbor in graph[node]:
                if neighbor not in visited:
                    cost = graph[node][neighbor]
                    if cost < min_cost:
                        min_edge = (node, neighbor)
                        min_cost = cost

        if min_edge:
            visited.add(min_edge[1])
            edge_list.append(min_edge)
            total_cost += min_cost

    return total_cost

total_cost = prims_algorithm(graph)
print(total_cost)

36


# NumPy Arrays Function

### Unique

In [35]:
arr=np.array([1,1,23,43,23,3,3,3])
x=np.unique(arr)
print(x)

[ 1  3 23 43]


In [37]:
x=np.unique(arr,return_index=True)
print(x)

(array([ 1,  3, 23, 43]), array([0, 5, 2, 3], dtype=int64))


# Resize

In [40]:
arr=np.array([1,1,23,43,23,3,3,3])
y=np.resize(arr,(2,4))
print(y)

[[ 1  1 23 43]
 [23  3  3  3]]


# Insert and Delete Function

In [41]:
arr=np.array([1,1,23,43,23,3,3,3])
v=np.insert(arr,3,500)
print(v)

[  1   1  23 500  43  23   3   3   3]


In [43]:
arr=np.array([[1,1,23,43],[32,34,5,6]])
v=np.insert(arr,1,500,axis=0)
print(v)

[[  1   1  23  43]
 [500 500 500 500]
 [ 32  34   5   6]]


In [44]:
arr=np.array([[1,1,23,43],[32,34,5,6]])
v=np.insert(arr,1,500,axis=1)
print(v)

[[  1 500   1  23  43]
 [ 32 500  34   5   6]]


In [47]:
arr=np.array([[1,1,23,43],[32,34,5,6]])
v=np.append(arr,[[100,200,300,60]],axis=0)
print(v)

[[  1   1  23  43]
 [ 32  34   5   6]
 [100 200 300  60]]


## Delete

In [49]:
var1=np.array([23,43,54,56])
print(var1)
dee=np.delete(var1,3)
print(dee)

[23 43 54 56]
[23 43 54]


# Matrix In NumPy Arrays

In [50]:
matr=np.matrix([[1,3,4],[45,67,54]])
print(matr)
print(type(matr))

[[ 1  3  4]
 [45 67 54]]
<class 'numpy.matrix'>


In [54]:
mat1=np.matrix([[1,3,4],[45,67,54],[34,56,76]])
mat2=np.matrix([[3,34,4],[45,6,54],[45,67,87]])
print(mat1+mat2)


[[  4  37   8]
 [ 90  73 108]
 [ 79 123 163]]


In [55]:
# Multiplication
print(mat1*mat2)

[[ 318  320  514]
 [5580 5550 8496]
 [6042 6584 9772]]


# Matrix Function In Numpy Arrays

### Transpose

In [56]:
mat1=np.matrix([[1,3,4],[45,67,54],[34,56,76]])
print(np.transpose(mat1))

[[ 1 45 34]
 [ 3 67 56]
 [ 4 54 76]]


#### Inverse

In [57]:
print(np.linalg.inv(mat1))

[[-1.20512821  0.002331    0.06177156]
 [ 0.92307692  0.03496503 -0.07342657]
 [-0.14102564 -0.02680653  0.03962704]]


In [58]:
print(np.linalg.det(mat1))

-1716.0000000000002


In [59]:
mat1=np.matrix([[1,3,4],[45,67,54],[34,56,76]])
print(np.linalg.matrix_power(mat1,2))

[[ 272  428  470]
 [4896 7648 7902]
 [5138 8110 8936]]
